[Icon Theme]
Name=High Contrast Large Print Inverse
Name[af]=Inverse hoë kontras groot druk
Name[am]=ትልቅ ከፍተኛ ልዩነት እና ትልቅ የፊደል ቅርጽ
Name[ar]=خطوط عريضة عالية التباين معكوسة
Name[as]=গাঢ় তাৰতম্য বিশিষ্ট ডাঙৰ বিপৰীত ছাপৰ অক্ষৰ
Name[ast]=Altu contraste grande invertíu
Name[az]=Böyük Yüksək Kontrast Tərs Çap
Name[be]=Інвэрсны высокі кантраст, вялікія літары
Name[be@latin]=Invertavany vysoki kantrast, vialiki, drukarski
Name[bg]=Обърнат висок контраст, едри елементи
Name[bn]=উচ্চ বৈসাদৃশ্য বিশিষ্ট বিপরীত বড় ছাপা অক্ষর
Name[bn_IN]=গাঢ় তারতম্য বিশিষ্ট বড় বিপরীত ছাপা অক্ষর
Name[bs]=Veliki Kontrast Ibiman Ispis Obrnuto
Name[ca]=Contrast alt invertit amb impressió gran
Name[ca@valencia]=Contrast alt invertit amb impressió gran
Name[crh]=Tersine Yüksek Tezat Büyük Basqı
Name[cs]=Inverzní vysoký kontrast velké písmo
Name[cy]=Cyferbynnedd Gref Testunau Mawr Gwrthdroedig
Name[da]=Højkontrast, stor inverteret
Name[de]=Hoher Kontrast, groß und invertiert
Name[dz]=ཁྱད་པར་ཆེ་བའི་ དཔར་བསྐྲུན་ཆེ་བ་ རྒྱབ་འགལ།
Name[el]=Large Print με αντιστροφή υψηλής αντίθεσης
Name[en@shaw]=·𐑣𐑲 ·𐑒𐑪𐑯𐑑𐑮𐑭𐑕𐑑 ·𐑤𐑸𐑡 ·𐑐𐑮𐑦𐑯𐑑 ·𐑦𐑯𐑝𐑻𐑕
Name[en_CA]=High Contrast Large Print Inverse
Name[en_GB]=High Contrast Large Print Inverse
Name[es]=Alto contraste grande invertido
Name[et]=Suur kontrast, pirakas, pööratud
Name[eu]=Alderantzizko kontraste altuko tipografi handia
Name[fa]=وارونگی با چاپ درشت و سایه‌روشن بالا
Name[fi]=Suuri kontrasti suurikokoisena (käänteinen)
Name[fr]=Contraste élevé inversé, grande taille
Name[fur]=Contrast elevât contrari, caràtars larcs
Name[ga]=Ardchodarsnacht Cló Mór Inbhéartach
Name[gl]=Alto contraste de impresión grande invertido
Name[gu]=ઊંચા તફાવતવાળી વિશાળ છાપ અોછી કરો
Name[he]=ניגוד גבוה הפוך בהדפסה מוגדלת
Name[hi]=अधिक विरोध विशाल प्रतिलोम
Name[hr]=Obrnuti visoki kontrast velikog ispisa
Name[hu]=Nagy kontraszt, nagy szöveg és inverz
Name[id]=Kontras Tinggi Terbalik Cetakan Besar
Name[is]=Miklar og stórar andstæður í öfugu prenti
Name[it]=Contrasto elevato inverso, caratteri grandi
Name[ja]=ハイ・コントラストの反転 (大)
Name[ka]=მაღალი კონტრასტი დიდიფორმატიანი,ინვერსიული ბეჭდვა
Name[kn]=ಹೆಚ್ಚು ವೈದೃಶ್ಯದ (ಕಾಂಟ್ರಾಸ್ಟಿನ) ದೊಡ್ಡ ಅಚ್ಚಿನ ವಿಲೋಮ
Name[ko]=고대비 확대 역상
Name[ky]=Басмалоо үчүн жогорку негативдүү контрастуулук
Name[li]=Hoeg kontras groete teks negatief
Name[lt]=Kontrastinga, inversinė, dideliu šriftu
Name[lv]=Spēcīga Kontrasta Liels Drukas Pretstats
Name[mai]=अधिक विरोध पैघ प्रतिलोम
Name[mg]=Sora-baventy be fifangarihana mifamadika
Name[mk]=Јак контраст, големи букви инверзно
Name[ml]=മിഴിവുറ്റ വലിയ പ്രിന്‍റ് സ്ക്രീന്‍ പശ്ചാത്തലം തിരിച്ചിട്ടു കാണുക
Name[mn]=Урвуулсан том хэвлэгдэх өндөр эрчимт
Name[mr]=उलटी उच्च विरोधाभास मोठे मुद्रण
Name[ms]=Cetakan Besar Kontras Tinggi Menyongsang
Name[nb]=Høy kontrast, stor skrift, omvendt
Name[nds]=Hoher Kontrast un grooter Druck, invertiert
Name[ne]=ठूलो मुद्रण विपरित उच्च ब्यतिरेक
Name[nl]=Hoog contrast grote tekst negatief
Name[nn]=Omvendt høg kontrast med stor skrift
Name[or]=ଅଧିକ ପ୍ରଭେଦ ବଡ଼ ଅକ୍ଷର ବିପରୀତ
Name[pa]=ਵੱਧ ਭਿੰਨਤਾ ਵੱਡਾ ਪਰਿੰਟ ਉਲਟ
Name[pl]=Duże o wysokim kontraście - negatyw
Name[pt]=Impressão Grande de Alto Contraste Invertido
Name[pt_BR]=Alto contraste letras grandes inverso
Name[ro]=Pictograme mari, contrast puternic și culori inversate
Name[ru]=Высококонтрастная негативная для печати
Name[si]=උච්ච ප්‍රභේදනයක් සහිත විශාල මුද්‍රණය ප්‍රතිලෝමය
Name[sk]=Inverzné vysokokontrastné veľké písmo
Name[sl]=Visok kontrast, velik izpis, obrnjeno
Name[sq]=Negativi i paraqitjes së zmadhuar me kontrast të lartë
Name[sr]=Увећани обрнути велики контраст
Name[sr@latin]=Uvećani obrnuti veliki kontrast
Name[sv]=Inverterad stor text med hög kontrast
Name[ta]=உயர்ந்த மாறுபாடு உள்ள அச்சின் எதிர்மறை 
Name[te]=అధిక కాంట్రాస్టు పెద్ద ముద్రణ విలోమం
Name[th]=สีตัดกัน อักษรใหญ่ กลับสี
Name[tr]=Tersine Yüksek Zıtlık Büyük Baskı
Name[ug]=يۇقۇرى ئېنىقلىقتا چوڭ قىلىپ تەتۈر بېسىش
Name[uk]=Висококонтрастна негативна для друку
Name[vi]=In cỡ lớn với độ tương phản cao ngược lại
Name[wa]=Grand contrasse å rviè avou grandès letes
Name[xh]=Ugqwetheko Loshicilelo Olukhulu Lomahluko Ophezulu
Name[zh_CN]=高对比大字体反色
Name[zh_HK]=高對比、大型、反色
Name[zh_TW]=高對比、大型、反色
Comment=Large Inverse High Contrast Icon Theme
Comment[af]=Groot inverse hoë kontras ikoontema
Comment[ar]=نسق أيقونات تباين عال معكوس وكبير
Comment[as]=বৃহৎ বিপৰীত গাঢ় তাৰতম্যৰ আইকন থিম
Comment[ast]=Tema d'iconos grandes d'altu contraste invertíu
Comment[be]=Тэма зь вялікімі кантраснымі інвэрснымі значкамі
Comment[be@latin]=Invertavany matyŭ vialikich ikon z vysokim kantrastam
Comment[bg]=Обратно висококонтрастни икони с едри елементи
Comment[bn]=বিপরীত উচ্চতর বৈশাদৃশ্যের আইকন থীম
Comment[bn_IN]=বৃহৎ বিপরীত গাঢ় তারতম্যের আইকন থিম
Comment[ca]=Tema d'icones grans de contrast alt invertit
Comment[ca@valencia]=Tema d'icones grans de contrast alt invertit
Comment[crh]=Büyük Tersine Yüksek Tezat İşaretçik Teması
Comment[cs]=Velké inverzní vysoce kontrastní ikony
Comment[da]=Højkontrast storikontema, inverteret
Comment[de]=Große Symbole mit hohem Kontrast, invertiert
Comment[el]=Μεγάλο θέμα εικονιδίων με αντιστροφή υψηλής αντίθεσης
Comment[en@shaw]=·𐑤𐑸𐑡 ·𐑦𐑯𐑝𐑻𐑕 ·𐑣𐑲 ·𐑒𐑪𐑯𐑑𐑮𐑭𐑕𐑑 𐑲𐑒𐑪𐑯 𐑔𐑰𐑥
Comment[en_GB]=Large Inverse High Contrast Icon Theme
Comment[es]=Tema de iconos grande de alto contraste invertido
Comment[et]=Suur pööratud kõrgkontrastne ikooniteema
Comment[eu]=Alderantzizko kontraste altuko ikono-gai handia
Comment[fi]=Suuri suurikontrastinen kuvaketeema (käänteinen)
Comment[fr]=Icônes de grandes tailles, avec contraste élevé inversé
Comment[ga]=Téama Deilbhíní Mór Inbhéartach Ardchodarsnachta
Comment[gl]=Tema de iconas grandes con alto contraste invertido
Comment[gu]=વિશાળ વિપરીત ઊંચો તફાવત આઇકોન થીમ
Comment[he]=ערכת נושא ניגוד גבוה הפוך
Comment[hi]=बड़ा विपरीत उच्च विरोधी प्रतीक प्रसंग
Comment[hr]=Tema s velikim slikama obrnutog velikog kontrasta
Comment[hu]=Nagy méretű, inverz magas kontrasztú ikontéma
Comment[id]=Tema Ikon Besar Kontras Tinggi Terbalik
Comment[it]=Tema icone grandi a contrasto elevato inverso
Comment[ja]=ハイ・コントラストなアイコン・テーマの反転 (大)
Comment[kn]=ದೊಡ್ದದಾದ ಹೆಚ್ಚು ವೈದೃಶ್ಯದ ಚಿಹ್ನೆಯ ಪರಿಸರವಿನ್ಯಾಸದ ವಿಲೋಮ
Comment[ko]=큰 고대비 역상 아이콘 테마
Comment[lt]=Didelė inversinė kontrastinga piktogramų tema
Comment[lv]=Liela inversa augsta kontrasta ikonu tēma
Comment[ml]=വലിയ കൂടുതല്‍ മിഴിവോട് കൂടി തിരിച്ചിട്ടു കാണാനുള്ള ചിഹ്നങ്ങളുടെ പ്രമേയം
Comment[mr]=मोठे उलटे उच्च विभन्नता चिन्ह सुत्रयोजना
Comment[nb]=Stort ikontema med høy kontrast, omvendt
Comment[nds]=Lütje Billers Thema mit grootem un invertiertem, hohem Kontrast
Comment[nl]=Groot pictogrammenthema met hoog contrast (negatief)
Comment[nn]=Stor omvendt høg kontrast ikondrakt
Comment[or]=ଅଧିକ ବିପରୀତ ପ୍ରଭେଦ ଚିତ୍ରସଙ୍କେତ ପ୍ରସଙ୍ଗ
Comment[pa]=ਵੱਧ ਭਿੰਨਤਾ ਉਲਟ ਆਈਕਾਨ ਥੀਮ
Comment[pl]=Zestaw dużych ikon o wysokim kontraście - negatyw
Comment[pt]=Tema de Ícones Grandes de Alto Contraste Invertido
Comment[pt_BR]=Tema de ícone grande de alto contraste inverso
Comment[ro]=Temă pictograme mari cu contrast invers puternic
Comment[ru]=Высококонтрастная негативная крупная тема значков
Comment[sk]=Inverzná téma veľkých vysokokontrastných ikon
Comment[sl]=Obrnjen visoko kontrastni slog
Comment[sr]=Тема иконица обрнутог великог контраста
Comment[sr@latin]=Tema ikonica obrnutog velikog kontrasta
Comment[sv]=Stort ikontema med inverterad hög kontrast
Comment[ta]=பெரிய தலைகீழான உயர் அடர்த்தியான சின்னத்தின் தீம்
Comment[te]=పెద్ద విలోమ అధిక కాంట్రాస్టు ప్రతిమ థీమ్
Comment[th]=ชุดไอคอนขนาดใหญ่ สีตัดกัน กลับสี
Comment[tr]=Büyük Tersine Yüksek Zıtlıkta Simge Teması
Comment[uk]=Висококонтрастна негативна тема з великими значками
Comment[vi]=Sắc thái biểu tượng tương phản cao ngược lớn
Comment[zh_CN]=大号高对比反色图标主题
Comment[zh_HK]=大型高對比反色圖示主題
Comment[zh_TW]=大型高對比反色圖示主題
Hidden=true

Directories=36x36/animations,48x48/actions,48x48/apps,48x48/categories,48x48/devices,48x48/emblems,48x48/filesystems,48x48/mimetypes,48x48/places,48x48/status

Inherits=gnome

[36x36/animations]
Size=36
Context=Animations
Type=Fixed

[48x48/actions]
Size=48
Context=Actions
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[48x48/categories]
Size=48
Context=Categories
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/emblems]
Size=48
Context=Emblems
Type=Fixed

[48x48/filesystems]
Size=48
Context=FileSystems
Type=Fixed

[48x48/mimetypes]
Size=48
Context=MimeTypes
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/status]
Size=48
Context=Status
Type=Fixed

