#!/bin/bash

# start these applets
# mate-volume-control-applet
# nm-applet
# mate-power-manager

for I in mate-volume-control-applet nm-applet mate-power-manager krb5-auth-dialog hexchat albert
do
	pid=$(pidof $I)
	if [ -z $pid ]
	then 
		# start the applet
		exec $I &
	#else
		# should I kill the pid
		#kill -9 $pid
	fi
done

pid=$(pidof autocutsel | wc -w)

if [ $pid != 2 ]
then
	# kill autocutsel and start fresh
	pkill -9 -f autocutsel
	autocutsel -fork
	autocutsel -selection PRIMARY -fork
fi
	
