#!/bin/bash

echo $1

case $1 in
    'up')
			cmd="amixer -D pulse sset Master 2%+"
    ;;
    'down')
			cmd="amixer -D pulse sset Master 2%-"
    ;;
		'mute')
			MUTED=`amixer -D pulse sget Master | grep -c off`
			if [ $MUTED == 0 ];
			then
				cmd="amixer -D pulse sset Master mute"
			else
				cmd="amixer -D pulse sset Master unmute"
			fi
		;;
		'playPause')
			# is the player running
			pidof -x pithos >/dev/null 2>&1
			if [ $? != 0 ];
			then
				pithos &
			else
				cmd='dbus-send --print-reply --dest=net.kevinmehall.Pithos /net/kevinmehall/Pithos net.kevinmehall.Pithos.PlayPause'
			fi
esac

exec $cmd 2>&1 > /dev/null
